version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
nuget:
  disable_publish_on_pr: true
build_script:
  - ps: (Get-Content SyncChanges\SyncChanges.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content SyncChanges\SyncChanges.csproj
  - ps: (Get-Content SyncChanges.Console\SyncChanges.Console.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content SyncChanges.Console\SyncChanges.Console.csproj
  - ps: (Get-Content SyncChanges.Service\SyncChanges.Service.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content SyncChanges.Service\SyncChanges.Service.csproj
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet pack --include-symbols --include-source -c Release SyncChanges
  - dotnet pack --include-symbols --include-source -c Release SyncChanges.Console
  - dotnet pack --include-symbols --include-source -c Release SyncChanges.Service
test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\coverage.xml" SyncChanges.Tests\SyncChanges.Tests.csproj /p:Include="[SyncChanges]*"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'SyncChanges\**\*.nupkg'
  - path: 'SyncChanges.Console\**\*.nupkg'
  - path: 'SyncChanges.Service\**\*.nupkg'
on_success:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          git config --global credential.helper store
          Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email "michael@ganss.org"
          git config --global user.name "Michael Ganss"
          git tag v$env:APPVEYOR_BUILD_VERSION
          git push origin --tags --porcelain
      }
